version: '3.5'

volumes:
  nextcloud_root:
  nextcloud_data:
  db:

networks:
  nextcloud_net:

services:
  db:
    image: mariadb:latest
    container_name: mariadb-docker
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - nextcloud_net
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=nextcloud
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=${DB_PWD}

  app:
    build: .
    container_name: nextcloud-docker
    restart: always
    depends_on:
      - db
    networks:
      - nextcloud_net
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - nextcloud_data:/srv/nextcloud/data
      - nextcloud_root:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PWD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${SERVER_IP}
      - NEXTCLOUD_DATA_DIR=${DATA_DIR}
